openapi: 3.0.0
info:
  title: watchlist
  version: '1.0'
  contact:
    name: Leor Brenman
  description: Stock Watch List API
servers:
  - url: 'http://localhost:3000'
paths: {}
components:
  schemas: {}
